apiVersion: apisix.apache.org/v1alpha1
kind: AmeshPluginConfig
metadata:
  name: ameshpluginconfig-sample
spec:
  plugins:
    - name: response-rewrite
      type: ""
      config: '{"body": "BODY_REWRITE", "headers": {"X-Header":"Rewrite"}}'
