// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on PluginsRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PluginsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PluginsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PluginsRequestMultiError,
// or nil if none found.
func (m *PluginsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PluginsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetInstance() == nil {
		err := PluginsRequestValidationError{
			field:  "Instance",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetInstance()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PluginsRequestValidationError{
					field:  "Instance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PluginsRequestValidationError{
					field:  "Instance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInstance()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PluginsRequestValidationError{
				field:  "Instance",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PluginsRequestMultiError(errors)
	}
	return nil
}

// PluginsRequestMultiError is an error wrapping multiple validation errors
// returned by PluginsRequest.ValidateAll() if the designated constraints
// aren't met.
type PluginsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PluginsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PluginsRequestMultiError) AllErrors() []error { return m }

// PluginsRequestValidationError is the validation error returned by
// PluginsRequest.Validate if the designated constraints aren't met.
type PluginsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PluginsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PluginsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PluginsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PluginsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PluginsRequestValidationError) ErrorName() string { return "PluginsRequestValidationError" }

// Error satisfies the builtin error interface
func (e PluginsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPluginsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PluginsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PluginsRequestValidationError{}

// Validate checks the field values on PluginsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PluginsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PluginsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PluginsResponseMultiError, or nil if none found.
func (m *PluginsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PluginsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetErrorMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PluginsResponseValidationError{
					field:  "ErrorMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PluginsResponseValidationError{
					field:  "ErrorMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetErrorMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PluginsResponseValidationError{
				field:  "ErrorMessage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetPlugins() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PluginsResponseValidationError{
						field:  fmt.Sprintf("Plugins[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PluginsResponseValidationError{
						field:  fmt.Sprintf("Plugins[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PluginsResponseValidationError{
					field:  fmt.Sprintf("Plugins[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PluginsResponseMultiError(errors)
	}
	return nil
}

// PluginsResponseMultiError is an error wrapping multiple validation errors
// returned by PluginsResponse.ValidateAll() if the designated constraints
// aren't met.
type PluginsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PluginsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PluginsResponseMultiError) AllErrors() []error { return m }

// PluginsResponseValidationError is the validation error returned by
// PluginsResponse.Validate if the designated constraints aren't met.
type PluginsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PluginsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PluginsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PluginsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PluginsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PluginsResponseValidationError) ErrorName() string { return "PluginsResponseValidationError" }

// Error satisfies the builtin error interface
func (e PluginsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPluginsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PluginsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PluginsResponseValidationError{}
