// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/v1/types.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on AmeshPlugin with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AmeshPlugin) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AmeshPlugin with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AmeshPluginMultiError, or
// nil if none found.
func (m *AmeshPlugin) ValidateAll() error {
	return m.validate(true)
}

func (m *AmeshPlugin) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _AmeshPlugin_Type_InLookup[m.GetType()]; !ok {
		err := AmeshPluginValidationError{
			field:  "Type",
			reason: "value must be in list [pre-req post-req]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := AmeshPluginValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetConfig()) < 2 {
		err := AmeshPluginValidationError{
			field:  "Config",
			reason: "value length must be at least 2 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AmeshPluginMultiError(errors)
	}
	return nil
}

// AmeshPluginMultiError is an error wrapping multiple validation errors
// returned by AmeshPlugin.ValidateAll() if the designated constraints aren't met.
type AmeshPluginMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AmeshPluginMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AmeshPluginMultiError) AllErrors() []error { return m }

// AmeshPluginValidationError is the validation error returned by
// AmeshPlugin.Validate if the designated constraints aren't met.
type AmeshPluginValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AmeshPluginValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AmeshPluginValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AmeshPluginValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AmeshPluginValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AmeshPluginValidationError) ErrorName() string { return "AmeshPluginValidationError" }

// Error satisfies the builtin error interface
func (e AmeshPluginValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAmeshPlugin.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AmeshPluginValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AmeshPluginValidationError{}

var _AmeshPlugin_Type_InLookup = map[string]struct{}{
	"pre-req":  {},
	"post-req": {},
}

// Validate checks the field values on AmeshPluginConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AmeshPluginConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AmeshPluginConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AmeshPluginConfigMultiError, or nil if none found.
func (m *AmeshPluginConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AmeshPluginConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPlugins() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AmeshPluginConfigValidationError{
						field:  fmt.Sprintf("Plugins[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AmeshPluginConfigValidationError{
						field:  fmt.Sprintf("Plugins[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AmeshPluginConfigValidationError{
					field:  fmt.Sprintf("Plugins[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if utf8.RuneCountInString(m.GetVersion()) < 1 {
		err := AmeshPluginConfigValidationError{
			field:  "Version",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AmeshPluginConfigMultiError(errors)
	}
	return nil
}

// AmeshPluginConfigMultiError is an error wrapping multiple validation errors
// returned by AmeshPluginConfig.ValidateAll() if the designated constraints
// aren't met.
type AmeshPluginConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AmeshPluginConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AmeshPluginConfigMultiError) AllErrors() []error { return m }

// AmeshPluginConfigValidationError is the validation error returned by
// AmeshPluginConfig.Validate if the designated constraints aren't met.
type AmeshPluginConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AmeshPluginConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AmeshPluginConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AmeshPluginConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AmeshPluginConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AmeshPluginConfigValidationError) ErrorName() string {
	return "AmeshPluginConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AmeshPluginConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAmeshPluginConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AmeshPluginConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AmeshPluginConfigValidationError{}
