/*
Copyright 2022 The Amesh Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/api7/amesh/apis/amesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAmeshPluginConfigs implements AmeshPluginConfigInterface
type FakeAmeshPluginConfigs struct {
	Fake *FakeApisixV1alpha1
	ns   string
}

var ameshpluginconfigsResource = schema.GroupVersionResource{Group: "apisix.apache.org", Version: "v1alpha1", Resource: "ameshpluginconfigs"}

var ameshpluginconfigsKind = schema.GroupVersionKind{Group: "apisix.apache.org", Version: "v1alpha1", Kind: "AmeshPluginConfig"}

// Get takes name of the ameshPluginConfig, and returns the corresponding ameshPluginConfig object, and an error if there is any.
func (c *FakeAmeshPluginConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ameshpluginconfigsResource, c.ns, name), &v1alpha1.AmeshPluginConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmeshPluginConfig), err
}

// List takes label and field selectors, and returns the list of AmeshPluginConfigs that match those selectors.
func (c *FakeAmeshPluginConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AmeshPluginConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ameshpluginconfigsResource, ameshpluginconfigsKind, c.ns, opts), &v1alpha1.AmeshPluginConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AmeshPluginConfigList{ListMeta: obj.(*v1alpha1.AmeshPluginConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.AmeshPluginConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ameshPluginConfigs.
func (c *FakeAmeshPluginConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ameshpluginconfigsResource, c.ns, opts))

}

// Create takes the representation of a ameshPluginConfig and creates it.  Returns the server's representation of the ameshPluginConfig, and an error, if there is any.
func (c *FakeAmeshPluginConfigs) Create(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.CreateOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ameshpluginconfigsResource, c.ns, ameshPluginConfig), &v1alpha1.AmeshPluginConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmeshPluginConfig), err
}

// Update takes the representation of a ameshPluginConfig and updates it. Returns the server's representation of the ameshPluginConfig, and an error, if there is any.
func (c *FakeAmeshPluginConfigs) Update(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.UpdateOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ameshpluginconfigsResource, c.ns, ameshPluginConfig), &v1alpha1.AmeshPluginConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmeshPluginConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAmeshPluginConfigs) UpdateStatus(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.UpdateOptions) (*v1alpha1.AmeshPluginConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ameshpluginconfigsResource, "status", c.ns, ameshPluginConfig), &v1alpha1.AmeshPluginConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmeshPluginConfig), err
}

// Delete takes name of the ameshPluginConfig and deletes it. Returns an error if one occurs.
func (c *FakeAmeshPluginConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ameshpluginconfigsResource, c.ns, name, opts), &v1alpha1.AmeshPluginConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAmeshPluginConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ameshpluginconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AmeshPluginConfigList{})
	return err
}

// Patch applies the patch and returns the patched ameshPluginConfig.
func (c *FakeAmeshPluginConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AmeshPluginConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ameshpluginconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AmeshPluginConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmeshPluginConfig), err
}
