---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apisix.apache.org
  resources:
  - ameshpluginconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - ameshpluginconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - apisix.apache.org
  resources:
  - ameshpluginconfigs/status
  verbs:
  - get
  - patch
  - update
