{
 "title": "Amesh Sidecars",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(apisix_http_status,service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(apisix_http_status,route)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(apisix_nginx_http_current_connections,instance)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(apisix_http_status,consumer)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(apisix_http_status,node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(apisix_http_requests_total, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(apisix_http_requests_total{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming Request Volume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(apisix_http_requests_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(apisix_http_status{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\",code!~\"5.*\"}[5m])) / sum(irate(apisix_http_status{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "XDS Config Shared Dict Free Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(apisix_shared_dict_free_space_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\",name=\"xds-config\"}) / sum(apisix_shared_dict_capacity_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\",name=\"xds-config\"})"
    }
   ]
  },
  {
   "title": "Nginx metric errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_metric_errors_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Ingress Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(apisix_bandwidth{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\",type=\"ingress\"}[1m]))"
    }
   ]
  },
  {
   "title": "Egress Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(apisix_bandwidth{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\",type=\"egress\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests By Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(apisix_http_status{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (namespace, pod, code), 0.001)",
     "legendFormat": "{{ namespace }}.{{ pod }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apisix_http_status{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\",code!~\"5.*\"}[5m])) by (pod, namespace) / sum(irate(apisix_http_status{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod, namespace)",
     "legendFormat": "{{ namespace }}.{{ pod }}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apisix_http_requests_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"accepted\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"handled\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nginx connection state",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=~\"active|reading|writing|waiting\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[30s])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second (RPS) by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (code)",
     "legendFormat": "HTTP Status:{{code}}"
    }
   ]
  },
  {
   "title": "Requests per second (RPS) per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "APISIX Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Amesh Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_sys_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_idle_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_released_bytes ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "process cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[2m])",
     "legendFormat": "process_cpu_seconds_total ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_sys_bytes ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_gc_sys_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"} - go_memstats_other_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_next_gc_bytes ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[2m])",
     "legendFormat": "go_memstats_mallocs_total ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes ({{namespace}}/{{pod}})"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_sys_bytes ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Goroutines ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"} - go_memstats_frees_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mallocs_total ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Quantile: {{quantile}} ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[2m])",
     "legendFormat": "go_memstats_lookups_total ({{namespace}}/{{pod}})"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}[2m])",
     "legendFormat": "go_memstats_alloc_bytes_total ({{namespace}}/{{pod}})"
    }
   ]
  }
 ]
}