/*
Copyright 2022 The Amesh Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/api7/amesh/apis/amesh/v1alpha1"
	scheme "github.com/api7/amesh/apis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AmeshPluginConfigsGetter has a method to return a AmeshPluginConfigInterface.
// A group's client should implement this interface.
type AmeshPluginConfigsGetter interface {
	AmeshPluginConfigs(namespace string) AmeshPluginConfigInterface
}

// AmeshPluginConfigInterface has methods to work with AmeshPluginConfig resources.
type AmeshPluginConfigInterface interface {
	Create(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.CreateOptions) (*v1alpha1.AmeshPluginConfig, error)
	Update(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.UpdateOptions) (*v1alpha1.AmeshPluginConfig, error)
	UpdateStatus(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.UpdateOptions) (*v1alpha1.AmeshPluginConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AmeshPluginConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AmeshPluginConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AmeshPluginConfig, err error)
	AmeshPluginConfigExpansion
}

// ameshPluginConfigs implements AmeshPluginConfigInterface
type ameshPluginConfigs struct {
	client rest.Interface
	ns     string
}

// newAmeshPluginConfigs returns a AmeshPluginConfigs
func newAmeshPluginConfigs(c *ApisixV1alpha1Client, namespace string) *ameshPluginConfigs {
	return &ameshPluginConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ameshPluginConfig, and returns the corresponding ameshPluginConfig object, and an error if there is any.
func (c *ameshPluginConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	result = &v1alpha1.AmeshPluginConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AmeshPluginConfigs that match those selectors.
func (c *ameshPluginConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AmeshPluginConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AmeshPluginConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ameshPluginConfigs.
func (c *ameshPluginConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a ameshPluginConfig and creates it.  Returns the server's representation of the ameshPluginConfig, and an error, if there is any.
func (c *ameshPluginConfigs) Create(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.CreateOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	result = &v1alpha1.AmeshPluginConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ameshPluginConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a ameshPluginConfig and updates it. Returns the server's representation of the ameshPluginConfig, and an error, if there is any.
func (c *ameshPluginConfigs) Update(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.UpdateOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	result = &v1alpha1.AmeshPluginConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		Name(ameshPluginConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ameshPluginConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *ameshPluginConfigs) UpdateStatus(ctx context.Context, ameshPluginConfig *v1alpha1.AmeshPluginConfig, opts v1.UpdateOptions) (result *v1alpha1.AmeshPluginConfig, err error) {
	result = &v1alpha1.AmeshPluginConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		Name(ameshPluginConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ameshPluginConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the ameshPluginConfig and deletes it. Returns an error if one occurs.
func (c *ameshPluginConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ameshPluginConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched ameshPluginConfig.
func (c *ameshPluginConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AmeshPluginConfig, err error) {
	result = &v1alpha1.AmeshPluginConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ameshpluginconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
