apiVersion: v1
kind: Pod
metadata:
  name: test-sidecar
spec:
  containers:
    - name: istio-proxy
      image: 10.0.0.20:5000/amesh-sidecar:dev
      #    ports:
      #    - containerPort: 9080
      #      protocol: TCP
      #      name: http-outbound
      #    - containerPort: 9081
      #      protocol: TCP
      #      name: http-inbound
      #    - containerPort: 17739
      #      protocol: TCP
      #      name: agent
      args:
        - run
        - --xds-config-source
        - "grpc://istiod.istio-system.svc.cluster.local:15010"
      env:
        - name: POD_NAME
          value: details-v1-79f774bdb9-s4d7w
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.name
        - name: POD_NAMESPACE
          value: test
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.namespace
      imagePullPolicy: Always
