apiVersion: v1
kind: ServiceAccount
metadata:
  name: amesh-controller-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amesh-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amesh-controller-role
subjects:
  - kind: ServiceAccount
    name: amesh-controller-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amesh-controller-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - apisix.apache.org
    resources:
      - ameshpluginconfigs
      - ameshpluginconfigs/status
    verbs:
      - '*'
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods", "endpoints", "services", "namespaces" ]
    verbs: [ "get", "list", "watch" ]
